server:
  port: 18084
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root