server:
  port: 18085
spring:
  cloud:
    gateway:
      routes:
        - id: Business
          uri: lb://Seata-Business
          predicates:
            - Path=/business/**
        - id: Seata-Item
          uri: lb://Seata-Item
          predicates:
            - Path=/itemInfo/**
        - id: Seata-Order
          uri: lb://Seata-Order
          predicates:
            - Path=/orderInfo/**
        - id: Seata-User
          uri: lb://Seata-User
          predicates:
            - Path=/userInfo/**